### PR TITLE
Update library version and references to SQLitePCLraw to 1.1.2

### PR DESCRIPTION
**Pull request by gentledepp**
updated library version to 1.1.2 and all references to SQLitePCLRaw also to 1.1.2

Added a package.ps1 script to create nuget packages

### CODE REVIEW

**Comment by bordoley** [comment]
Is this blocking you. I'm in the middle of a large work project, so I'm not sure I will be able to get to reviewing this or pushing an update til next weekend.

**Comment by gentledepp** [comment]
no it is not
we've our own nuget package repo ;-)

but for an official SyncWinRT release we'd need it of course

**Comment by gentledepp** [comment]
#40  is fixed and I added a unittest for this of course.

One more thing:
The _SQLitePCL.pretty.tests.x86_ were actually broken: They referenced an old SQLitePCL.raw.dll (the new ones do not have a dot between SQLitePCL and raw)
In order to get them to work, I had to introduce a common base class "TestBase" which (only on windows) calls `SQLitePCL.Batteries.Init();`

now the tests work file - also on Android and iOS.
But I do not know, if I broke any intent of you?

**Comment by gentledepp** [comment]
now also supports creating [nuget symbol packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages).

Maybe you can publish the symbol packages as well on the next release? (see the link above)

**Comment by bordoley** [comment]
I just wanted to update you that this will probably have to wait until the middle of next week. I have a project I need to finish up over the weekend, but I really do apologize for the delay.

**Comment by gentledepp** [comment]
Could you please merge in the near future?
We are using this library (including the fix) in another github project and we really need to make a release soon:
[SyncWinRT](https://github.com/Mimetis/SyncWinRT/)

**Comment by bordoley** [comment]
As much as I would like to maintain this package, I simply don't have the time anymore. I've added you as a collaborator to the main repo. Feel free to push changes as you like.

**Comment by gentledepp** [comment]
Thanks man 👍

**Comment by bordoley** [comment]
Do you want to manage the nuget packages as well?

**Comment by gentledepp** [comment]
Yeah that'd be awesome. That way I could create new packages

**Comment by bordoley** [comment]
What is your nuget username?

**Comment by gentledepp** [comment]
*gentledepp*
or am I mistaken? :-|

**Comment by gentledepp** [comment]
oh... sry
my fault -

**Comment by gentledepp** [comment]
I do not have one yet.
Maybe I can create one just for this repo

**Comment by gentledepp** [comment]
ok.. I can't.
So it is:
alexander.marek@outlook.com

**Comment by bordoley** [comment]
I also added you as a maintainer of the repo I was using to host the documentation, though it would probably be easier to move the documentation into a branch of this repo.

**Pull request closed without merging**
